server:
  port: 8080
spring:
  application:
    name: ccip-gateway
  cloud:
    gateway:
      routes:
      - id: ccip-patient
        uri: lb://ccip-patient
        predicates:
        - Path=/patient/**
      - id: ccip-encounter
        uri: lb://ccip-encounter
        predicates:
        - Path=/encounter/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    #enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG